modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
modId="snowrealmagic"
version="${file.jarVersion}"
displayName="Snow! Real Magic!"
authors="Snownee, minzhi, WZD"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snowrealmagic"
description="Tweak vanilla snow layer."

[[dependencies.snowrealmagic]]
    modId="kiwi"
    mandatory=true
    versionRange="[9, 10)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowrealmagic]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowrealmagic]]
    modId="rubidium"
    mandatory=false
    versionRange="[0.6.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.snowrealmagic]
    catalogueItemIcon="minecraft:snow_block" #Support for Catalogue mod
