modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "snowrealmagic"
version = "${file.jarVersion}"
displayName = "Snow! Real Magic!"
authors = "Snownee, minzhi, WZD"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/snowrealmagic"
description = "Tweaks vanilla snow layer"

[[dependencies.snowrealmagic]]
modId = "kiwi"
mandatory = true
versionRange = "[11, 12)"
ordering = "NONE"
side = "BOTH"

[modproperties.snowrealmagic]
catalogueItemIcon = "minecraft:snow_block" #Support for Catalogue mod
