modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="snowrealmagic"
version="${file.jarVersion}"
displayName="Snow! Real Magic!"
authors="Snownee, minzhi, WZD"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snowrealmagic"
description="Tweak vanilla snow layer."

[[dependencies.snowrealmagic]]
    modId="kiwi"
    mandatory=true
    versionRange="[6, 7)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowrealmagic]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowrealmagic]]
    modId="jade"
    mandatory=false
    versionRange="[4.2,)"
    ordering="BEFORE"
    side="BOTH"

[modproperties.snowrealmagic]
    catalogueItemIcon="minecraft:snow_block" #Support for Catalogue mod
